name: easy_dispose_rxdart
version: 1.1.0

homepage: https://github.com/xal/easy_dispose
description: Extension to easy_dispose package. Help dispose rxdart classes like Subject.
repository: https://github.com/xal/easy_dispose

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  easy_dispose: ">=1.0.0 <2.0.0"
  rxdart: ">=0.26.0 <=1.0.0"

dev_dependencies:
  dart_code_metrics: ^4.4.0
  lints: ^1.0.1
  test: ^1.17.9
  all_lint_rules_community: ^0.0.4
