name: easy_dispose_provider
version: 1.0.2

homepage: https://github.com/xal/easy_dispose
description: Extension to easy_dispose package. Dispose provider classes via DisposableStreamProvider, DisposableProvider, etc
repository: https://github.com/xal/easy_dispose

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  easy_dispose: ">=1.0.0 <=1.1.0"
  flutter:
    sdk: flutter
  provider: ">=5.0.0 <=7.0.0"

dev_dependencies:
  dart_code_metrics: ^4.4.0
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  matcher: ^0.12.10
  all_lint_rules_community: ^0.0.4
