name: easy_dispose
version: 1.1.0

homepage: https://github.com/xal/easy_dispose
description: Common interface to dispose different things. Always call dispose() instead of cancel(), stop(), etc.
repository: https://github.com/xal/easy_dispose

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  dart_code_metrics: ^4.4.0
  lints: ^1.0.1
  test: ^1.17.9
  all_lint_rules_community: ^0.0.4
