name: easy_dispose_flutter
version: 1.0.1

homepage: https://github.com/xal/easy_dispose
description: Extension to easy_dispose package. Dispose Flutter API classes like TextEditingController, FocusNode, ChangeNotifier listeners, etc.
repository: https://github.com/xal/easy_dispose

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  easy_dispose: ">=1.0.0 <=1.1.0"

  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^4.0.1
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  matcher: ^0.12.10
