name: easy_dispose_example
version: 1.0.0
publish_to: none

description: An example project that uses easy_dispose

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # only for this repo
  easy_dispose:
    path: ../
  # usage example
  # easy_dispose: version
