name: easy_dispose_flutter_example
version: 1.0.0
publish_to: none

description: An example project that uses easy_dispose_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  # only for this repo
  easy_dispose_flutter:
    path: ../
  # usage example
  # easy_dispose_flutter: version

  flutter:
    sdk: flutter
